apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: radarr
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: radarr.local
    http:
      paths:
      - path: /
        backend:
          serviceName: radarr
          servicePort: 7878
  